const express = require("express");
const bcrypt = require("bcryptjs");

// 관리자 인증용 디버그 라우터를 생성한다.
function createAdminAuthRouter() {
  const router = express.Router();

  // 쿼리스트링 비밀번호를 받아 bcrypt 해시를 생성해 반환한다.
  router.get("/debug/hash", async (req, res) => {
    const plainPassword = String(req.query?.password || "").trim();

    if (!plainPassword) {
      return res.status(400).json({
        ok: false,
        message: "password 쿼리값을 입력해 주세요.",
      });
    }

    try {
      const passwordHash = await bcrypt.hash(plainPassword, 12);

      console.log("[admin-auth] debug hash generated by GET", {
        length: plainPassword.length,
        passwordHash,
      });

      return res.json({
        ok: true,
        password: plainPassword,
        passwordHash,
      });
    } catch (error) {
      console.error("[admin-auth] debug hash failed by GET", error);
      return res.status(500).json({
        ok: false,
        message: "해시 생성 중 오류가 발생했습니다.",
      });
    }
  });

  // 평문 비밀번호를 받아 bcrypt 해시를 생성해 반환한다.
  router.post("/debug/hash", async (req, res) => {
    const plainPassword = String(req.body?.password || "").trim();

    if (!plainPassword) {
      return res.status(400).json({
        ok: false,
        message: "password 값을 입력해 주세요.",
      });
    }

    try {
      const passwordHash = await bcrypt.hash(plainPassword, 12);

      console.log("[admin-auth] debug hash generated", {
        length: plainPassword.length,
        passwordHash,
      });

      return res.json({
        ok: true,
        password: plainPassword,
        passwordHash,
      });
    } catch (error) {
      console.error("[admin-auth] debug hash failed", error);
      return res.status(500).json({
        ok: false,
        message: "해시 생성 중 오류가 발생했습니다.",
      });
    }
  });

  return router;
}

module.exports = {
  createAdminAuthRouter,
};